
spring:
  kafka:
    bootstrap-servers: 192.168.255.165:9092
    consumer:
      enable-auto-commit: false
    listener:
      ack-mode: manual

server:
  port: 8080

kafka:
  num:
    partitions: 2 #Topic分区数
    replica: 3 #副本数